export const dummyData = [
  {
    id: 1,
    title: "First Item",
    description: "This is the first item",
    images: ["https://via.placeholder.com/150"],
    createdBy: "John Doe",
    createdAt: "2021-01-01",
    updatedAt: "2021-01-01",
  },
  {
    id: 2,
    title: "Second Item",
    description: "This is the second item",
    images: ["https://via.placeholder.com/150"],
    createdBy: "Jane Doe",
    createdAt: "2021-02-01",
    updatedAt: "2021-02-01",
  },
  {
    id: 3,
    title: "Third Item",
    description: "This is the third item",
    images: ["https://via.placeholder.com/150"],
    createdBy: "Jim Doe",
    createdAt: "2021-03-01",
    updatedAt: "2021-03-01",
  },
  {
    id: 4,
    title: "Fourth Item",
    description: "This is the fourth item",
    images: ["https://via.placeholder.com/150"],
    createdBy: "Jill Doe",
    createdAt: "2021-04-01",
    updatedAt: "2021-04-01",
  },
  {
    id: 5,
    title: "Fifth Item",
    description: "This is the fifth item",
    images: ["https://via.placeholder.com/150"],
    createdBy: "Jack Doe",
    createdAt: "2021-05-01",
    updatedAt: "2021-05-01",
  },
  {
    id: 6,
    title: "Sixth Item",
    description: "This is the sixth item",
    images: ["https://via.placeholder.com/150"],
    createdBy: "Jerry Doe",
    createdAt: "2021-06-01",
    updatedAt: "2021-06-01",
  },
];

export const dummyCategories = [
  "Italian",
  "Mexican",
  "Chinese",
  "Indian",
  "American",
  "Thai",
  "Japanese",
  "Mediterranean",
  "French",
  "Spanish",
];
